version: "3"

tasks:
  build:
    cmds:
      - go build -o ipl
    desc: "Build the Go project"

  test:
    cmds:
      - go test ./...
    desc: "Run tests"

  lint:
    cmds:
      - golangci-lint run
    desc: "Lint the code"
