[formatter.nix]
command = "alejandra"
includes = ["*.nix"]

[formatter.go]
command = "gofmt"
includes = ["*.go"]

[formatter.prettier]
command = "prettier"
options = ["--write"]
includes = ["*.yaml", "*.yml", "*.md"]

[formatter.toml]
command = "taplo"
options = ["format"]
includes = ["*.toml"]
